# Generated by Django 5.0.6 on 2024-06-21 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=None, editable=False, verbose_name='Date')),
                ('mode', models.CharField(choices=[('ca', 'Call'), ('ma', 'E-Mail'), ('me', 'Meeting')], default='ca', max_length=2, verbose_name='Mode of interaction')),
                ('note', models.CharField(max_length=200)),
                ('customer', models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('salesman', models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
