# Generated by Django 5.0.6 on 2024-06-21 17:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_interaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
    ]
