# Generated by Django 5.0.6 on 2024-06-21 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_interaction_customer_alter_interaction_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interaction',
        ),
    ]
