# Generated by Django 5.0.6 on 2024-06-21 18:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0005_delete_interaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('stage', models.CharField(choices=[('co', 'Contact'), ('de', 'Demo'), ('pr', 'Proposal'), ('ne', 'Negotiation'), ('wo', 'Sale won'), ('po', 'Post sale')], default='co', max_length=2, verbose_name='Stage of sale')),
                ('note', models.CharField(max_length=200)),
                ('customer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('salesman', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('mode', models.CharField(choices=[('ca', 'Call'), ('ma', 'E-Mail'), ('me', 'Meeting')], default='ca', max_length=2, verbose_name='Mode of interaction')),
                ('note', models.CharField(max_length=200)),
                ('sale', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sales.sale')),
            ],
        ),
    ]
